@baseUrl = http://localhost:8000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzE4MDY2LCJpYXQiOjE3NDAxNDUyNjYsImp0aSI6ImU5ZDI5YzgwZmEzNjRkZDRhNjVhZGVkNzg3YjI4NzA0IiwidXNlcl9pZCI6Mn0.x1aMo0uQcpVq67msk4S9NAZIysOgF-pIX-_6h1baZew

POST {{baseUrl}}/accounts/register/
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@mail.com",
  "password": "Pass=1234",
  "pin": "1234"
}


###
POST {{baseUrl}}/api/token/
Content-Type: application/json

{
  "username": "testuser",
  "password": "Pass=1234"
}


###
POST {{baseUrl}}/wallet/deposit/
Content-Type: application/json
Authorization: {{token}}

{
  "amount": 100,
  "pin": "1234"
}

###
POST {{baseUrl}}/wallet/withdraw/
Content-Type: application/json
Authorization: {{token}}

{
  "amount": 10,
  "pin": "1234"
}

###
GET {{baseUrl}}/wallet/balance
Content-Type: application/json
Authorization: {{token}}

{
  "pin": "1234"
}

###
POST {{baseUrl}}/wallet/transfer_money/
Content-Type: application/json
Authorization: {{token}}

{
  "recipient_wallet": "3024300255",
  "amount": 10,
  "pin": "1234"
}

###
POST {{baseUrl}}/wallet/receive_payment_qr_scan/
Content-Type: application/json
Authorization: {{token}}

{
    "amount": 10.00
}

###
POST {{baseUrl}}/wallet/send_payment_qr_scan/
Content-Type: application/json
Authorization: {{token}}

{
    "qr_data": "gAAAAABnuUEYDepe0w0LxUVTVir0UQnypLh_na6AZlUntFUZlvykxCS_Xhuotc39MLoqVpNc6pvaXnflWe3d64ChFXbJYaBH6A=="
}
