# Generated by Django 5.1.5 on 2025-02-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0003_alter_wallet_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_pin',
            field=models.CharField(max_length=220),
        ),
    ]
