# Generated by Django 5.1.5 on 2025-02-19 11:59

import ewallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0004_alter_wallet_wallet_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionqrscan',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=ewallet.models.upload_dir),
        ),
    ]
